### ISSUE TITLE
Add more zombies

### ISSUE THREAD

**Issue by thestokkan** [thestokkan/zombie-game#11]
https://github.com/thestokkan/zombie-game/blob/3387350d6d850b362232807473750819c4c973ed/Pseudocode_game_class.txt#L59

**Comment by thestokkan** [comment]
@Zohla, hadde ikke du gjort dette? Var derfor jeg la den til 'in progress'.

**Comment by Zohla** [comment]
Jo, jeg kan pynte på den:)
